// Generated by CoffeeScript 1.10.0
var AccountUpdaterDailyReport, AttributeSetter,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

AccountUpdaterDailyReport = (function(superClass) {
  extend(AccountUpdaterDailyReport, superClass);

  function AccountUpdaterDailyReport(attributes) {
    AccountUpdaterDailyReport.__super__.constructor.call(this, attributes);
  }

  return AccountUpdaterDailyReport;

})(AttributeSetter);

exports.AccountUpdaterDailyReport = AccountUpdaterDailyReport;

//# sourceMappingURL=account_updater_daily_report.js.map
