// Generated by CoffeeScript 1.10.0
var AddOn, AttributeSetter,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

AddOn = (function(superClass) {
  extend(AddOn, superClass);

  function AddOn() {
    return AddOn.__super__.constructor.apply(this, arguments);
  }

  return AddOn;

})(AttributeSetter);

exports.AddOn = AddOn;

//# sourceMappingURL=add_on.js.map
