// Generated by CoffeeScript 1.10.0
var AddOn, AddOnGateway, Gateway,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AddOn = require('./add_on').AddOn;

Gateway = require('./gateway').Gateway;

AddOnGateway = (function(superClass) {
  extend(AddOnGateway, superClass);

  function AddOnGateway(gateway) {
    this.gateway = gateway;
    this.config = this.gateway.config;
  }

  AddOnGateway.prototype.all = function(callback) {
    return this.gateway.http.get((this.config.baseMerchantPath()) + "/add_ons", this.createResponseHandler("add_on", AddOn, callback));
  };

  return AddOnGateway;

})(Gateway);

exports.AddOnGateway = AddOnGateway;

//# sourceMappingURL=add_on_gateway.js.map
