// Generated by CoffeeScript 1.10.0
var Address, AttributeSetter,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

Address = (function(superClass) {
  extend(Address, superClass);

  function Address() {
    return Address.__super__.constructor.apply(this, arguments);
  }

  return Address;

})(AttributeSetter);

exports.Address = Address;

//# sourceMappingURL=address.js.map
