// Generated by CoffeeScript 1.10.0
var AmexExpressCheckoutCard, AttributeSetter,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

AmexExpressCheckoutCard = (function(superClass) {
  extend(AmexExpressCheckoutCard, superClass);

  function AmexExpressCheckoutCard(attributes) {
    AmexExpressCheckoutCard.__super__.constructor.call(this, attributes);
  }

  return AmexExpressCheckoutCard;

})(AttributeSetter);

exports.AmexExpressCheckoutCard = AmexExpressCheckoutCard;

//# sourceMappingURL=amex_express_checkout_card.js.map
