// Generated by CoffeeScript 1.10.0
var AndroidPayCard, AttributeSetter,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

AndroidPayCard = (function(superClass) {
  extend(AndroidPayCard, superClass);

  function AndroidPayCard(attributes) {
    AndroidPayCard.__super__.constructor.call(this, attributes);
    if (attributes) {
      this.cardType = attributes.virtualCardType;
      this.last4 = attributes.virtualCardLast4;
    }
  }

  return AndroidPayCard;

})(AttributeSetter);

exports.AndroidPayCard = AndroidPayCard;

//# sourceMappingURL=android_pay_card.js.map
