// Generated by CoffeeScript 1.10.0
var AttributeSetter;

AttributeSetter = (function() {
  function AttributeSetter(attributes) {
    var key, value;
    for (key in attributes) {
      value = attributes[key];
      this[key] = value;
    }
  }

  return AttributeSetter;

})();

exports.AttributeSetter = AttributeSetter;

//# sourceMappingURL=attribute_setter.js.map
