// Generated by CoffeeScript 1.10.0
var ClientTokenGateway, DEFAULT_VERSION, ErrorResponse, Gateway, exceptions,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Gateway = require('./gateway').Gateway;

ErrorResponse = require('./error_response').ErrorResponse;

exceptions = require('./exceptions');

DEFAULT_VERSION = 2;

ClientTokenGateway = (function(superClass) {
  extend(ClientTokenGateway, superClass);

  function ClientTokenGateway(gateway) {
    this.gateway = gateway;
    this.config = this.gateway.config;
  }

  ClientTokenGateway.prototype.generate = function(params, callback) {
    var err, responseHandler;
    if (params == null) {
      params = {};
    }
    params.version || (params.version = DEFAULT_VERSION);
    err = this.validateParams(params);
    if (err) {
      return callback(err, null);
    }
    params = {
      client_token: params
    };
    responseHandler = this.responseHandler(callback);
    return this.gateway.http.post((this.config.baseMerchantPath()) + "/client_token", params, responseHandler);
  };

  ClientTokenGateway.prototype.validateParams = function(params) {
    var invalidOptions, name, options;
    if (params.customerId || !params.options) {
      return;
    }
    options = ["makeDefault", "verifyCard", "failOnDuplicatePaymentMethod"];
    invalidOptions = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = options.length; i < len; i++) {
        name = options[i];
        if (params.options[name]) {
          results.push(name);
        }
      }
      return results;
    })();
    if (invalidOptions.length > 0) {
      return exceptions.UnexpectedError("Invalid keys: " + invalidOptions.toString());
    } else {
      return null;
    }
  };

  ClientTokenGateway.prototype.responseHandler = function(callback) {
    return function(err, response) {
      if (err) {
        return callback(err, response);
      }
      if (response.clientToken) {
        response.success = true;
        response.clientToken = response.clientToken.value;
        return callback(null, response);
      } else if (response.apiErrorResponse) {
        return callback(null, new ErrorResponse(response.apiErrorResponse));
      }
    };
  };

  return ClientTokenGateway;

})(Gateway);

exports.ClientTokenGateway = ClientTokenGateway;

//# sourceMappingURL=client_token_gateway.js.map
