// Generated by CoffeeScript 1.10.0
var AttributeSetter, CoinbaseAccount,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

CoinbaseAccount = (function(superClass) {
  extend(CoinbaseAccount, superClass);

  function CoinbaseAccount(attributes) {
    CoinbaseAccount.__super__.constructor.call(this, attributes);
  }

  return CoinbaseAccount;

})(AttributeSetter);

exports.CoinbaseAccount = CoinbaseAccount;

//# sourceMappingURL=coinbase_account.js.map
