// Generated by CoffeeScript 1.10.0
var AdvancedSearch, CreditCard, CreditCardVerification, CreditCardVerificationSearch,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AdvancedSearch = require('./advanced_search').AdvancedSearch;

CreditCard = require('./credit_card').CreditCard;

CreditCardVerification = require('./credit_card_verification').CreditCardVerification;

CreditCardVerificationSearch = (function(superClass) {
  extend(CreditCardVerificationSearch, superClass);

  function CreditCardVerificationSearch() {
    return CreditCardVerificationSearch.__super__.constructor.apply(this, arguments);
  }

  CreditCardVerificationSearch.textFields("billingAddressDetailsPostalCode", "creditCardCardholderName", "customerEmail", "customerId", "id", "paymentMethodToken");

  CreditCardVerificationSearch.equalityFields("creditCardExpirationDate");

  CreditCardVerificationSearch.partialMatchFields("creditCardNumber");

  CreditCardVerificationSearch.multipleValueField("creditCardCardType", {
    "allows": CreditCard.CardType.All()
  });

  CreditCardVerificationSearch.multipleValueField("status", {
    "allows": CreditCardVerification.StatusType.All()
  });

  CreditCardVerificationSearch.multipleValueField("ids");

  CreditCardVerificationSearch.rangeFields("createdAt");

  return CreditCardVerificationSearch;

})(AdvancedSearch);

exports.CreditCardVerificationSearch = CreditCardVerificationSearch;

//# sourceMappingURL=credit_card_verification_search.js.map
