// Generated by CoffeeScript 1.10.0
var Disbursement, DisbursementGateway, Gateway,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Gateway = require('./gateway').Gateway;

Disbursement = require('./disbursement').Disbursement;

DisbursementGateway = (function(superClass) {
  extend(DisbursementGateway, superClass);

  function DisbursementGateway(gateway) {
    this.gateway = gateway;
    this.config = this.gateway.config;
  }

  DisbursementGateway.prototype.transactions = function(disbursement, callback) {
    var transactionIds;
    transactionIds = disbursement.transactionIds;
    return this.gateway.transaction.search((function(search) {
      return search.ids()["in"](transactionIds);
    }), callback);
  };

  return DisbursementGateway;

})(Gateway);

exports.DisbursementGateway = DisbursementGateway;

//# sourceMappingURL=disbursement_gateway.js.map
