// Generated by CoffeeScript 1.10.0
var AttributeSetter, DisbursementDetails,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

DisbursementDetails = (function(superClass) {
  extend(DisbursementDetails, superClass);

  function DisbursementDetails() {
    return DisbursementDetails.__super__.constructor.apply(this, arguments);
  }

  DisbursementDetails.prototype.isValid = function() {
    return this.disbursementDate != null;
  };

  return DisbursementDetails;

})(AttributeSetter);

exports.DisbursementDetails = DisbursementDetails;

//# sourceMappingURL=disbursement_details.js.map
