// Generated by CoffeeScript 1.10.0
var AttributeSetter, Dispute, TransactionDetails,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

TransactionDetails = require('./transaction_details').TransactionDetails;

Dispute = (function(superClass) {
  extend(Dispute, superClass);

  Dispute.Status = {
    Open: 'open',
    Lost: 'lost',
    Won: 'won'
  };

  Dispute.Reason = {
    CancelledRecurringTransaction: 'cancelled_recurring_transaction',
    CreditNotProcessed: 'credit_not_processed',
    Duplicate: 'duplicate',
    Fraud: 'fraud',
    General: 'general',
    InvalidAccount: 'invalid_account',
    NotRecognized: 'not_recognized',
    ProductNotReceived: 'product_not_received',
    ProductUnsatisfactory: 'product_unsatisfactory',
    Retrieval: 'retrieval',
    TransactionAmountDiffers: 'transaction_amount_differs'
  };

  Dispute.Kind = {
    Chargeback: 'chargeback',
    PreArbitration: 'pre_arbitration',
    Retrieval: 'retrieval'
  };

  function Dispute(attributes) {
    Dispute.__super__.constructor.call(this, attributes);
    this.transactionDetails = new TransactionDetails(attributes.transaction);
  }

  return Dispute;

})(AttributeSetter);

exports.Dispute = Dispute;

//# sourceMappingURL=dispute.js.map
