// Generated by CoffeeScript 1.10.0
exports.authenticationError = 'authenticationError';

exports.authorizationError = 'authorizationError';

exports.downForMaintenanceError = 'downForMaintenanceError';

exports.invalidSignatureError = 'invalidSignatureError';

exports.invalidChallengeError = 'invalidChallengeError';

exports.invalidTransparentRedirectHashError = 'invalidTransparentRedirectHashError';

exports.notFoundError = 'notFoundError';

exports.serverError = 'serverError';

exports.testOperationPerformedInProductionError = 'testOperationPerformedInProductionError';

exports.unexpectedError = 'unexpectedError';

exports.upgradeRequired = 'upgradeRequired';

//# sourceMappingURL=error_types.js.map
