// Generated by CoffeeScript 1.10.0
var AttributeSetter, FacilitatorDetails,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

FacilitatorDetails = (function(superClass) {
  extend(FacilitatorDetails, superClass);

  function FacilitatorDetails(attributes) {
    FacilitatorDetails.__super__.constructor.call(this, attributes);
  }

  return FacilitatorDetails;

})(AttributeSetter);

exports.FacilitatorDetails = FacilitatorDetails;

//# sourceMappingURL=facilitator_details.js.map
