// Generated by CoffeeScript 1.10.0
var AttributeSetter, MerchantAccount,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

MerchantAccount = (function(superClass) {
  extend(MerchantAccount, superClass);

  MerchantAccount.Status = {
    Pending: "pending",
    Active: "active",
    Suspended: "suspended"
  };

  MerchantAccount.FundingDestination = {
    Bank: "bank",
    Email: "email",
    MobilePhone: "mobile_phone"
  };

  function MerchantAccount(attributes) {
    MerchantAccount.__super__.constructor.call(this, attributes);
    if (attributes.masterMerchantAccount) {
      this.masterMerchantAccount = new MerchantAccount(attributes.masterMerchantAccount);
    }
  }

  return MerchantAccount;

})(AttributeSetter);

exports.MerchantAccount = MerchantAccount;

//# sourceMappingURL=merchant_account.js.map
