// Generated by CoffeeScript 1.10.0
var AttributeSetter, Merchant,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

Merchant = (function(superClass) {
  extend(Merchant, superClass);

  function Merchant(attributes) {
    Merchant.__super__.constructor.call(this, attributes);
  }

  return Merchant;

})(AttributeSetter);

exports.Merchant = Merchant;

//# sourceMappingURL=merchant.js.map
