// Generated by CoffeeScript 1.10.0
var AttributeSetter, PartnerMerchant,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

PartnerMerchant = (function(superClass) {
  extend(PartnerMerchant, superClass);

  function PartnerMerchant() {
    return PartnerMerchant.__super__.constructor.apply(this, arguments);
  }

  return PartnerMerchant;

})(AttributeSetter);

exports.PartnerMerchant = PartnerMerchant;

//# sourceMappingURL=partner_merchant.js.map
