// Generated by CoffeeScript 1.10.0
var AttributeSetter, PayPalAccount,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

PayPalAccount = (function(superClass) {
  extend(PayPalAccount, superClass);

  function PayPalAccount(attributes) {
    PayPalAccount.__super__.constructor.call(this, attributes);
  }

  return PayPalAccount;

})(AttributeSetter);

exports.PayPalAccount = PayPalAccount;

//# sourceMappingURL=paypal_account.js.map
