// Generated by CoffeeScript 1.10.0
var Gateway, Plan, PlanGateway,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Gateway = require('./gateway').Gateway;

Plan = require('./plan').Plan;

PlanGateway = (function(superClass) {
  extend(PlanGateway, superClass);

  function PlanGateway(gateway) {
    this.gateway = gateway;
    this.config = this.gateway.config;
  }

  PlanGateway.prototype.all = function(callback) {
    return this.gateway.http.get((this.config.baseMerchantPath()) + "/plans", this.createResponseHandler("plan", Plan, callback));
  };

  return PlanGateway;

})(Gateway);

exports.PlanGateway = PlanGateway;

//# sourceMappingURL=plan_gateway.js.map
