// Generated by CoffeeScript 1.10.0
var AttributeSetter, RiskData,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

RiskData = (function(superClass) {
  extend(RiskData, superClass);

  function RiskData(attributes) {
    RiskData.__super__.constructor.call(this, attributes);
  }

  return RiskData;

})(AttributeSetter);

exports.RiskData = RiskData;

//# sourceMappingURL=risk_data.js.map
