// Generated by CoffeeScript 1.10.0
var AttributeSetter, SettlementBatchSummary,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

SettlementBatchSummary = (function(superClass) {
  extend(SettlementBatchSummary, superClass);

  function SettlementBatchSummary() {
    return SettlementBatchSummary.__super__.constructor.apply(this, arguments);
  }

  return SettlementBatchSummary;

})(AttributeSetter);

exports.SettlementBatchSummary = SettlementBatchSummary;

//# sourceMappingURL=settlement_batch_summary.js.map
