// Generated by CoffeeScript 1.10.0
var Gateway, SettlementBatchSummary, SettlementBatchSummaryGateway, Util,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Gateway = require('./gateway').Gateway;

Util = require('./util').Util;

SettlementBatchSummary = require('./settlement_batch_summary').SettlementBatchSummary;

SettlementBatchSummaryGateway = (function(superClass) {
  extend(SettlementBatchSummaryGateway, superClass);

  function SettlementBatchSummaryGateway(gateway) {
    this.gateway = gateway;
    this.config = this.gateway.config;
  }

  SettlementBatchSummaryGateway.prototype.generate = function(criteria, callback) {
    return this.gateway.http.post((this.config.baseMerchantPath()) + "/settlement_batch_summary", {
      settlementBatchSummary: criteria
    }, this.responseHandler(criteria, callback));
  };

  SettlementBatchSummaryGateway.prototype.responseHandler = function(criteria, callback) {
    return this.createResponseHandler("settlementBatchSummary", SettlementBatchSummary, (function(_this) {
      return function(err, response) {
        return callback(null, _this.underscoreCustomField(criteria, response));
      };
    })(this));
  };

  SettlementBatchSummaryGateway.prototype.underscoreCustomField = function(criteria, response) {
    var camelCustomField, i, len, record, ref;
    if (response.success && ('groupByCustomField' in criteria)) {
      camelCustomField = Util.toCamelCase(criteria.groupByCustomField);
      ref = response.settlementBatchSummary.records;
      for (i = 0, len = ref.length; i < len; i++) {
        record = ref[i];
        record[criteria.groupByCustomField] = record[camelCustomField];
        record[camelCustomField] = null;
      }
    }
    return response;
  };

  return SettlementBatchSummaryGateway;

})(Gateway);

exports.SettlementBatchSummaryGateway = SettlementBatchSummaryGateway;

//# sourceMappingURL=settlement_batch_summary_gateway.js.map
