// Generated by CoffeeScript 1.10.0
var AdvancedSearch, Subscription, SubscriptionSearch,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AdvancedSearch = require('./advanced_search').AdvancedSearch;

Subscription = require('./subscription').Subscription;

SubscriptionSearch = (function(superClass) {
  extend(SubscriptionSearch, superClass);

  function SubscriptionSearch() {
    return SubscriptionSearch.__super__.constructor.apply(this, arguments);
  }

  SubscriptionSearch.multipleValueField("inTrialPeriod");

  SubscriptionSearch.multipleValueField("ids");

  SubscriptionSearch.textFields("id", "transactionId");

  SubscriptionSearch.multipleValueOrTextField("planId");

  SubscriptionSearch.multipleValueField("status", {
    "allows": Subscription.Status.All()
  });

  SubscriptionSearch.multipleValueField("merchantAccountId");

  SubscriptionSearch.rangeFields("price", "daysPastDue", "billingCyclesRemaining", "nextBillingDate");

  return SubscriptionSearch;

})(AdvancedSearch);

exports.SubscriptionSearch = SubscriptionSearch;

//# sourceMappingURL=subscription_search.js.map
