// Generated by CoffeeScript 1.10.0
var AttributeSetter, ThreeDSecureInfo,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

ThreeDSecureInfo = (function(superClass) {
  extend(ThreeDSecureInfo, superClass);

  function ThreeDSecureInfo(attributes) {
    ThreeDSecureInfo.__super__.constructor.call(this, attributes);
  }

  return ThreeDSecureInfo;

})(AttributeSetter);

exports.ThreeDSecureInfo = ThreeDSecureInfo;

//# sourceMappingURL=three_d_secure_info.js.map
