// Generated by CoffeeScript 1.10.0
var AndroidPayCard, ApplePayCard, AttributeSetter, CoinbaseAccount, CreditCard, DisbursementDetails, Dispute, FacilitatorDetails, PayPalAccount, RiskData, ThreeDSecureInfo, Transaction,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

AttributeSetter = require('./attribute_setter').AttributeSetter;

ApplePayCard = require('./apple_pay_card').ApplePayCard;

AndroidPayCard = require('./android_pay_card').AndroidPayCard;

CreditCard = require('./credit_card').CreditCard;

PayPalAccount = require('./paypal_account').PayPalAccount;

CoinbaseAccount = require('./coinbase_account').CoinbaseAccount;

DisbursementDetails = require('./disbursement_details').DisbursementDetails;

Dispute = require('./dispute').Dispute;

FacilitatorDetails = require('./facilitator_details').FacilitatorDetails;

RiskData = require('./risk_data').RiskData;

ThreeDSecureInfo = require('./three_d_secure_info').ThreeDSecureInfo;

Transaction = (function(superClass) {
  extend(Transaction, superClass);

  Transaction.CreatedUsing = {
    FullInformation: 'full_information',
    Token: 'token'
  };

  Transaction.EscrowStatus = {
    HoldPending: 'hold_pending',
    Held: 'held',
    ReleasePending: 'release_pending',
    Released: 'released',
    Refunded: 'refunded'
  };

  Transaction.Source = {
    Api: 'api',
    ControlPanel: 'control_panel',
    Recurring: 'recurring'
  };

  Transaction.Type = {
    Credit: 'credit',
    Sale: 'sale',
    All: function() {
      var all, key, value;
      all = [];
      for (key in this) {
        value = this[key];
        if (key !== 'All') {
          all.push(value);
        }
      }
      return all;
    }
  };

  Transaction.GatewayRejectionReason = {
    ApplicationIncomplete: 'application_incomplete',
    Avs: 'avs',
    Cvv: 'cvv',
    AvsAndCvv: 'avs_and_cvv',
    Duplicate: 'duplicate',
    Fraud: 'fraud',
    ThreeDSecure: 'three_d_secure'
  };

  Transaction.IndustryData = {
    Lodging: 'lodging',
    TravelAndCruise: 'travel_cruise'
  };

  Transaction.Status = {
    AuthorizationExpired: 'authorization_expired',
    Authorizing: 'authorizing',
    Authorized: 'authorized',
    GatewayRejected: 'gateway_rejected',
    Failed: 'failed',
    ProcessorDeclined: 'processor_declined',
    Settled: 'settled',
    Settling: 'settling',
    SettlementConfirmed: 'settlement_confirmed',
    SettlementDeclined: 'settlement_declined',
    SettlementPending: 'settlement_pending',
    SubmittedForSettlement: 'submitted_for_settlement',
    Voided: 'voided',
    All: function() {
      var all, key, value;
      all = [];
      for (key in this) {
        value = this[key];
        if (key !== 'All') {
          all.push(value);
        }
      }
      return all;
    }
  };

  function Transaction(attributes) {
    var disputeAttributes;
    Transaction.__super__.constructor.call(this, attributes);
    this.creditCard = new CreditCard(attributes.creditCard);
    this.paypalAccount = new PayPalAccount(attributes.paypal);
    this.coinbaseAccount = new CoinbaseAccount(attributes.coinbaseAccount);
    this.applePayCard = new ApplePayCard(attributes.applePay);
    this.androidPayCard = new AndroidPayCard(attributes.androidPayCard);
    this.disbursementDetails = new DisbursementDetails(attributes.disbursementDetails);
    if (attributes.disputes != null) {
      this.disputes = (function() {
        var i, len, ref, results;
        ref = attributes.disputes;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          disputeAttributes = ref[i];
          results.push(new Dispute(disputeAttributes));
        }
        return results;
      })();
    }
    if (attributes.facilitatorDetails) {
      this.facilitatorDetails = new FacilitatorDetails(attributes.facilitatorDetails);
    }
    if (attributes.riskData) {
      this.riskData = new RiskData(attributes.riskData);
    }
    if (attributes.threeDSecureInfo) {
      this.threeDSecureInfo = new ThreeDSecureInfo(attributes.threeDSecureInfo);
    }
  }

  Transaction.prototype.isDisbursed = function() {
    return this.disbursementDetails.isValid();
  };

  return Transaction;

})(AttributeSetter);

exports.Transaction = Transaction;

//# sourceMappingURL=transaction.js.map
