// Generated by CoffeeScript 1.10.0
var Util, semver;

semver = require('semver');

Util = (function() {
  function Util() {}

  Util.convertObjectKeysToUnderscores = function(obj) {
    var item, key, newKey, newObj, value;
    newObj = {};
    for (key in obj) {
      value = obj[key];
      newKey = Util.toUnderscore(key);
      if (value instanceof Array) {
        newObj[newKey] = (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = value.length; i < len; i++) {
            item = value[i];
            results.push(typeof item === 'object' ? Util.convertObjectKeysToUnderscores(item) : item);
          }
          return results;
        })();
      } else if (typeof value === 'object') {
        if (value instanceof Date || value === null) {
          newObj[newKey] = value;
        } else {
          newObj[newKey] = Util.convertObjectKeysToUnderscores(value);
        }
      } else {
        newObj[newKey] = value;
      }
    }
    return newObj;
  };

  Util.convertNodeToObject = function(obj) {
    var i, item, j, key, len, len1, newArray, newObj, results, value;
    if (typeof obj === 'object' && obj['@']) {
      if (obj['@'].type === 'array') {
        newArray = [];
        for (key in obj) {
          value = obj[key];
          if (key !== '@') {
            if (value instanceof Array) {
              for (i = 0, len = value.length; i < len; i++) {
                item = value[i];
                newArray.push(this.convertNodeToObject(item));
              }
            } else {
              newArray.push(this.convertNodeToObject(value));
            }
          }
        }
        return newArray;
      } else if (obj['@'].type === 'collection') {
        newObj = {};
        for (key in obj) {
          value = obj[key];
          if (key !== '@') {
            newObj[this.toCamelCase(key)] = this.convertNodeToObject(value);
          }
        }
        return newObj;
      } else if (obj['@'].nil === 'true') {
        return null;
      } else if (obj['@'].type === 'integer') {
        return parseInt(obj['#']);
      } else if (obj['@'].type === 'boolean') {
        return obj['#'] === 'true';
      } else {
        return obj['#'];
      }
    } else if (obj instanceof Array) {
      results = [];
      for (j = 0, len1 = obj.length; j < len1; j++) {
        item = obj[j];
        results.push(this.convertNodeToObject(item));
      }
      return results;
    } else if (typeof obj === 'object' && this.objectIsEmpty(obj)) {
      return '';
    } else if (typeof obj === 'object') {
      newObj = {};
      for (key in obj) {
        value = obj[key];
        newObj[this.toCamelCase(key)] = this.convertNodeToObject(value);
      }
      return newObj;
    } else {
      return obj;
    }
  };

  Util.objectIsEmpty = function(obj) {
    var key, value;
    for (key in obj) {
      value = obj[key];
      return false;
    }
    return true;
  };

  Util.arrayIsEmpty = function(array) {
    if (!(array instanceof Array)) {
      return false;
    }
    if (array.length > 0) {
      return false;
    }
    return true;
  };

  Util.toCamelCase = function(string) {
    return string.replace(/([\-\_][a-z0-9])/g, function(match) {
      return match.toUpperCase().replace('-', '').replace('_', '');
    });
  };

  Util.toUnderscore = function(string) {
    return string.replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2').replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
  };

  Util.flatten = function(array) {
    while (this._containsArray(array)) {
      array = array.reduce((function(_this) {
        return function(first, rest) {
          first = first instanceof Array ? first : [first];
          rest = rest instanceof Array ? _this.flatten(rest) : rest;
          return first.concat(rest);
        };
      })(this));
    }
    return array;
  };

  Util.merge = function(obj1, obj2) {
    var key, value;
    for (key in obj2) {
      value = obj2[key];
      obj1[key] = value;
    }
    return obj1;
  };

  Util.without = function(array1, array2) {
    var i, len, newArray, value;
    newArray = [];
    for (i = 0, len = array1.length; i < len; i++) {
      value = array1[i];
      if (!this._containsValue(array2, value)) {
        newArray.push(value);
      }
    }
    return newArray;
  };

  Util.supportsStreams2 = function() {
    return semver.satisfies(process.version, '>=0.10');
  };

  Util.flattenKeys = function(obj, prefix) {
    var key, keys, value;
    if (prefix == null) {
      prefix = null;
    }
    keys = [];
    for (key in obj) {
      value = obj[key];
      if (typeof value === 'object') {
        keys.push(Util.flattenKeys(value, key));
      } else {
        if (prefix) {
          keys.push(prefix + "[" + key + "]");
        } else {
          keys.push(key);
        }
      }
    }
    return this.flatten(keys);
  };

  Util.verifyKeys = function(validKeys, obj, deprecate) {
    var invalidKeys;
    invalidKeys = this.without(this.flattenKeys(obj), validKeys);
    if (invalidKeys.length > 0) {
      return deprecate("invalid keys: " + invalidKeys.join(", ") + ". In future releases we'll throw exceptions on keys we do not recognize. It is recommended to fix this now to avoid payment processing interruptions.");
    }
  };

  Util._containsValue = function(array, element) {
    return array.indexOf(element) !== -1;
  };

  Util._containsArray = function(array) {
    var element, i, len;
    for (i = 0, len = array.length; i < len; i++) {
      element = array[i];
      if (element instanceof Array) {
        return true;
      }
    }
  };

  return Util;

})();

exports.Util = Util;

//# sourceMappingURL=util.js.map
