// Generated by CoffeeScript 1.10.0
var Util, ValidationError, ValidationErrorsCollection;

Util = require('./util').Util;

ValidationError = require('./validation_error').ValidationError;

ValidationErrorsCollection = (function() {
  function ValidationErrorsCollection(errorAttributes) {
    var key, val;
    this.validationErrors = {};
    this.errorCollections = {};
    for (key in errorAttributes) {
      val = errorAttributes[key];
      if (key === 'errors') {
        this.buildErrors(val);
      } else {
        this.errorCollections[key] = new ValidationErrorsCollection(val);
      }
    }
  }

  ValidationErrorsCollection.prototype.buildErrors = function(errors) {
    var base, i, item, key, len, results;
    results = [];
    for (i = 0, len = errors.length; i < len; i++) {
      item = errors[i];
      key = Util.toCamelCase(item.attribute);
      (base = this.validationErrors)[key] || (base[key] = []);
      results.push(this.validationErrors[key].push(new ValidationError(item)));
    }
    return results;
  };

  ValidationErrorsCollection.prototype.deepErrors = function() {
    var errors, key, ref, ref1, val;
    errors = [];
    ref = this.validationErrors;
    for (key in ref) {
      val = ref[key];
      errors = errors.concat(val);
    }
    ref1 = this.errorCollections;
    for (key in ref1) {
      val = ref1[key];
      errors = errors.concat(val.deepErrors());
    }
    return errors;
  };

  ValidationErrorsCollection.prototype["for"] = function(name) {
    return this.errorCollections[name];
  };

  ValidationErrorsCollection.prototype.forIndex = function(index) {
    return this.errorCollections["index" + index];
  };

  ValidationErrorsCollection.prototype.on = function(name) {
    return this.validationErrors[name];
  };

  return ValidationErrorsCollection;

})();

exports.ValidationErrorsCollection = ValidationErrorsCollection;

//# sourceMappingURL=validation_errors_collection.js.map
