// Generated by CoffeeScript 1.10.0
var CreditCardDefaults;

CreditCardDefaults = {
  CountryOfIssuance: "USA",
  IssuingBank: "NETWORK ONLY"
};

exports.CreditCardDefaults = CreditCardDefaults;

//# sourceMappingURL=credit_card_defaults.js.map
