// Generated by CoffeeScript 1.10.0
var TransactionAmounts;

TransactionAmounts = {
  Authorize: "1000.00",
  Decline: "2000.00",
  Fail: "3000.00"
};

exports.TransactionAmounts = TransactionAmounts;

//# sourceMappingURL=transaction_amounts.js.map
